// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { customPreload } from './customPreload';
import { householdMembersSectionComplete } from '../../common/helper';
import { getResponse } from 'evolution-common/lib/utils/helpers';
import * as odSurveyHelper from 'evolution-common/lib/services/odSurvey/helpers';

export const currentSectionName: string = 'household';
const previousSectionName: SectionConfig['previousSection'] = 'home';
const nextSectionName: SectionConfig['nextSection'] = 'personsTrips';

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Ménage',
        en: 'Household'
    },
    navMenu: {
        type: 'inNav',
        menuName: {
            fr: 'Ménage',
            en: 'Household'
        }
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    preload: customPreload,
    // Allow to click on the section menu
    enableConditional: function (interview) {
        return isSectionCompleted({ interview, sectionName: previousSectionName });
    },
    // Allow to click on the section menu
    completionConditional: function (interview) {
        return householdMembersSectionComplete(interview);
    },
    onSectionExit: (interview, iterationContext) => {
        const personsCount = odSurveyHelper.countPersons({ interview });
        const householdSize = getResponse(interview, 'household.size', null);

        // Make the household size match the number of household members in this section
        if (householdSize !== personsCount) {
            return {
                ['response.household.size']: personsCount
            };
        }
        return undefined;
    }
};

export default sectionConfig;
