// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';

export const widgetsNames: SectionConfig['widgets'] = [
    'activePersonTitle',
    'buttonSwitchPerson',
    'personTripsTitle',
    'personVisitedPlacesMap',
    'personTrips',
    'buttonConfirmNextSection'
];

export const personTripsWidgetsNames: SectionConfig['widgets'] = ['segmentIntro', 'segments', 'buttonSaveTrip'];

export const segmentsWidgetsNames: SectionConfig['widgets'] = [
    'segmentSameModeAsReverseTrip',
    'segmentModePre',
    'segmentMode',
    'segmentHowToBus',
    'segmentPaidForParking',
    'segmentVehicleOccupancy',
    'segmentDriver',
    'segmentBusLines',
    'segmentBusLinesWarning',
    'segmentOnDemandType',
    'tripJunctionQueryString',
    'tripJunctionGeography',
    'segmentHasNextMode'
];
