// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import * as homeWidgets from './sections/home/widgets';
import * as householdWidgets from './sections/household/widgets';
import * as personsTripsWidgets from './sections/personsTrips/widgets';
import * as selectPersonWidgets from './sections/selectPerson/widgets';
import * as tripsIntroWidgets from './sections/tripsIntro/widgets';
import * as visitedPlacesWidgets from './sections/visitedPlaces/widgets';
import * as segmentsWidgets from './sections/segments/widgets';
import * as travelBehaviorWidgets from './sections/travelBehavior/widgets';
import * as longDistanceWidgets from './sections/longDistance/widgets';
import * as endWidgets from './sections/end/widgets';
import * as completedWidgets from './sections/completed/widgets';

// Define all the widgets
const widgets: { [key: string]: any } = {};

// Define all the sections widgets
const sectionsWidgets = [
    homeWidgets,
    householdWidgets,
    personsTripsWidgets,
    selectPersonWidgets,
    tripsIntroWidgets,
    visitedPlacesWidgets,
    segmentsWidgets,
    travelBehaviorWidgets,
    longDistanceWidgets,
    endWidgets,
    completedWidgets
];

// Loop all sections and add their widgets to the widgets object
sectionsWidgets.forEach((section) => {
    for (const widget in section) {
        widgets[widget] = section[widget];
    }
});

// Export all the widgets
export { widgets };
