// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customChoices from './customChoices';
import * as customHelpPopup from '../../common/customHelpPopup';
import * as customValidations from '../../common/customValidations';
import * as customLabels from '../../common/customLabels';

// activePersonTitle

// buttonSwitchPerson

// Custom because it's a popup and it has a condition on interviewable person count, not household
export const personNewPerson = customWidgets.personNewPerson;

export const personWhoWillAnswerForThisPerson: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.whoWillAnswerForThisPerson',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        return t('tripsIntro:personWhoWillAnswerForThisPerson', {
            nickname,
            context: activePerson?.gender || activePerson?.sexAssignedAtBirth
        });
    },
    choices: customChoices.whoAnswersCustomChoices,
    conditional: customConditionals.if2OrMorePersons14OrMoreYearsOldCustomConditional,
    validations: validations.requiredValidation
};

// Custom label because has journey date. This widget should be in Evolution
export const personDidTrips: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personDidTrips',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.personDidTripsCustomLabel,
    helpPopup: customHelpPopup.assignedDateHelpPopup,
    choices: choices.yesNo,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

// Custom choices because of the presence of the assigned date in the string, conditional depends on trip count and main label has dates. This widget should be in Evolution
export const personDidTripsConfirm: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personDidTripsConfirm',
    twoColumns: false,
    containsHtml: false,
    label: customLabels.personDidTripsConfirmCustomLabel,
    choices: customChoices.personDidTripsConfirmCustomChoices,
    conditional: customConditionals.personDeclaredTripsCustomConditional,
    validations: validations.requiredValidation
};

// Custom label because has journey date. This widget should be in Evolution
export const visitedPlacesIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.visitedPlacesIntro',
    containsHtml: true,
    text: customLabels.visitedPlacesIntroCustomLabel,
    conditional: conditionals.personDidTripsConditional
};

// Custom label because has journey dates. This widget should be in Evolution
export const personDeparturePlaceIsHome: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceIsHome',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.departurePlaceIsHomeCustomLabel,
    choices: choices.yesNo,
    conditional: customConditionals.personDidTripsAndDeparturePlaceNotSetCustomConditional,
    validations: customValidations.personDeparturePlaceIsHomeRequiredWithSpecificTestCustomValidation
};

export const personDeparturePlaceOther: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceOther',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('tripsIntro:personDeparturePlaceOther', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.departurePlaceOtherChoices,
    conditional: customConditionals.departurePlaceOtherCustomConditional,
    validations: validations.requiredValidation
};

// Custom choices because it has the departure place type in the labels
//
// FIXME: personOutOfTerritory : implication · Issue #45 · chairemobilite/od_mtl
export const personOutOfTerritory: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.outOfTerritory',
    twoColumns: false,
    containsHtml: false,
    label: customLabels.personOutOfTerritoryCustomLabel,
    choices: customChoices.outOfTerritoryCustomChoices,
    conditional: conditionals.outOfTerritoryConditional,
    validations: validations.requiredValidation
};

// Custom choices because it is the household members
export const personOutOfTerritoryMembers: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.outOfTerritoryMembers',
    twoColumns: false,
    containsHtml: false,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('tripsIntro:personOutOfTerritoryMembers', {
            nickname,
            count: countPersons
        });
    },
    choices: customChoices.outOfTerritoryMembersCustomChoices,
    conditional: conditionals.outOfTerritoryMembersConditional,
    validations: customValidations.personOutOfTerritoryMembersCustomValidation
};

export const tripsIntro_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'tripsIntro.save',
    label: (t: TFunction) => t('tripsIntro:tripsIntro_save'),
    conditional: defaultConditional
};

export const tripsIntroOutro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'tripsIntroOutro',
    containsHtml: true,
    text: (t: TFunction) => t('tripsIntro:tripsIntroOutro'),
    conditional: defaultConditional
};
