// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import { type ChoiceType } from 'evolution-common/lib/services/questionnaire/types';
import _escape from 'lodash/escape';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as conditionals from './conditionals';
import * as customConditionals from './customConditionals';

export const yes: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:yes.yes')
    }
];

export const no: ChoiceType[] = [
    {
        value: 'no',
        label: (t: TFunction) => t('choices:no.no')
    }
];

export const other: ChoiceType[] = [
    {
        value: 'other',
        label: (t: TFunction) => t('choices:other.other')
    }
];

export const otherWithoutSpecify: ChoiceType[] = [
    {
        value: 'other',
        label: (t: TFunction) => t('choices:otherWithoutSpecify.other')
    }
];

export const dontKnow: ChoiceType[] = [
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:dontKnow.dontKnow')
    }
];

export const preferNotToAnswer: ChoiceType[] = [
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:preferNotToAnswer.preferNotToAnswer')
    }
];

export const yesNo: ChoiceType[] = [...yes, ...no];

export const yesNoDontKnow: ChoiceType[] = [...yesNo, ...dontKnow];

export const yesNoPreferNotToAnswer: ChoiceType[] = [...yes, ...no, ...preferNotToAnswer];

export const homeIsMain: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:homeIsMain.yes')
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:homeIsMain.no')
    }
];

export const maleFemalePreferNotAnswer: ChoiceType[] = [
    {
        value: 'female',
        label: (t: TFunction) => t('choices:maleFemalePreferNotAnswer.female')
    },
    {
        value: 'male',
        label: (t: TFunction) => t('choices:maleFemalePreferNotAnswer.male')
    },
    ...preferNotToAnswer
];

export const maleFemaleCustomPreferNotToAnswer: ChoiceType[] = [
    {
        value: 'female',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.female')
    },
    {
        value: 'male',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.male')
    },
    {
        value: 'custom',
        label: (t: TFunction) => t('choices:maleFemaleCustomPreferNotToAnswer.custom')
    },
    ...preferNotToAnswer
];

export const participationStatusWorker: ChoiceType[] = [
    {
        value: 'fullTime',
        label: (t: TFunction) => t('choices:participationStatusWorker.fullTime')
    },
    {
        value: 'partTime',
        label: (t: TFunction) => t('choices:participationStatusWorker.partTime')
    },
    ...no
];

export const participationStatusStudent: ChoiceType[] = [
    {
        value: 'fullTime',
        label: (t: TFunction) => t('choices:participationStatusStudent.fullTime')
    },
    {
        value: 'partTime',
        label: (t: TFunction) => t('choices:participationStatusStudent.partTime')
    },
    ...no
];

export const personOccupation: ChoiceType[] = [
    {
        value: 'fullTimeWorker',
        label: (t: TFunction) => t('choices:personOccupation.fullTimeWorker'),
        hidden: true
    },
    {
        value: 'partTimeWorker',
        label: (t: TFunction) => t('choices:personOccupation.partTimeWorker'),
        hidden: true
    },
    {
        value: 'workerAndStudent',
        label: (t: TFunction) => t('choices:personOccupation.workerAndStudent'),
        hidden: true
    },
    {
        value: 'fullTimeStudent',
        label: (t: TFunction) => t('choices:personOccupation.fullTimeStudent'),
        hidden: true
    },
    {
        value: 'partTimeStudent',
        label: (t: TFunction) => t('choices:personOccupation.partTimeStudent'),
        hidden: true
    },
    {
        value: 'retired',
        label: (t: TFunction) => t('choices:personOccupation.retired'),
        conditional: conditionals.ifAge40OrMoreConditional
    },
    {
        value: 'atHome',
        label: (t: TFunction) => t('choices:personOccupation.atHome')
    },
    {
        value: 'unemployed',
        label: (t: TFunction) => t('choices:personOccupation.unemployed')
    },
    {
        value: 'parentalOrSickLeave',
        label: (t: TFunction) => t('choices:personOccupation.parentalOrSickLeave')
    },
    {
        value: 'longTermDisability',
        label: (t: TFunction) => t('choices:personOccupation.longTermDisability')
    },
    {
        value: 'volunteer',
        label: (t: TFunction) => t('choices:personOccupation.volunteer')
    },
    ...otherWithoutSpecify,
    ...preferNotToAnswer
];

export const transitPassType: ChoiceType[] = [
    {
        value: 'transitPassARTM',
        label: (t: TFunction) => t('choices:transitPassType.transitPassARTM'),
        conditional: conditionals.ifAge64OrLessConditional
    },
    {
        value: 'transitPassARTMWithElderly',
        label: (t: TFunction) => t('choices:transitPassType.transitPassARTMWithElderly'),
        conditional: conditionals.ifAge65OrMoreConditional
    },
    {
        value: 'tickets',
        label: (t: TFunction) => t('choices:transitPassType.tickets')
    },
    {
        value: 'employee',
        label: (t: TFunction) => t('choices:transitPassType.employee')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:transitPassType.other')
    },
    ...dontKnow
];

export const transitFareType: ChoiceType[] = [
    {
        value: 'A',
        label: (t: TFunction) => t('choices:transitFareType.A')
    },
    {
        value: 'AB',
        label: (t: TFunction) => t('choices:transitFareType.AB')
    },
    {
        value: 'ABC',
        label: (t: TFunction) => t('choices:transitFareType.ABC')
    },
    {
        value: 'ABCD',
        label: (t: TFunction) => t('choices:transitFareType.ABCD')
    },
    {
        value: 'bus',
        label: (t: TFunction) => t('choices:transitFareType.bus')
    },
    {
        value: 'busCD',
        label: (t: TFunction) => t('choices:transitFareType.busCD')
    },
    {
        value: 'opusWithTicketsOnly',
        label: (t: TFunction) => t('choices:transitFareType.opusWithTicketsOnly')
    },
    {
        value: 'otherTerritory',
        label: (t: TFunction) => t('choices:transitFareType.otherTerritory')
    },
    ...other,
    {
        value: 'none',
        label: (t: TFunction) => t('choices:transitFareType.none')
    },
    ...dontKnow
];

export const transitFareWarning: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:transitFareWarning.yes')
    }
];

export const workPlaceTypeChoices: ChoiceType[] = [
    {
        value: 'onLocation',
        label: (t: TFunction, interview, path) => {
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceTypeChoices.onLocation', {
                count: countPersons
            });
        }
    },
    {
        value: 'hybrid',
        label: (t: TFunction, interview, path) => {
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceTypeChoices.hybrid', {
                count: countPersons
            });
        }
    },
    {
        value: 'remote',
        label: (t: TFunction, interview, path) => {
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceTypeChoices.remote', {
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithUsualPlace',
        label: (t: TFunction, interview, path) => {
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceTypeChoices.onTheRoadWithUsualPlace', {
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithoutUsualPlace',
        label: (t: TFunction, interview, path) => {
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceTypeChoices.onTheRoadWithoutUsualPlace', {
                count: countPersons
            });
        }
    }
];

export const longDistanceFrequencyChoices: ChoiceType[] = [
    {
        value: '00_00',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.00_00')
    },
    {
        value: '01_03',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.01_03')
    },
    {
        value: '04_12',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.04_12')
    },
    {
        value: '13_99',
        label: (t: TFunction) => t('choices:longDistanceFrequencyChoices.13_99')
    }
];

export const householdIncomeChoices: ChoiceType[] = [
    {
        value: '000000_014999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.000000_014999')
    },
    {
        value: '015000_029999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.015000_029999')
    },
    {
        value: '030000_044999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.030000_044999')
    },
    {
        value: '045000_059999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.045000_059999')
    },
    {
        value: '060000_079999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.060000_079999')
    },
    {
        value: '080000_099999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.080000_099999')
    },
    {
        value: '100000_149999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.100000_149999')
    },
    {
        value: '150000_199999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.150000_199999')
    },
    {
        value: '200000_999999',
        label: (t: TFunction) => t('choices:householdIncomeChoices.200000_999999')
    },
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:householdIncomeChoices.dontKnow')
    },
    {
        value: 'refusal',
        label: (t: TFunction) => t('choices:householdIncomeChoices.refusal')
    }
];

export const householdOwnershipChoices: ChoiceType[] = [
    {
        value: 'tenant',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.tenant')
    },
    {
        value: 'owner',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.owner')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.other')
    },
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:householdOwnershipChoices.preferNotToAnswer')
    }
];

export const departurePlaceOtherChoices: ChoiceType[] = [
    {
        value: 'otherParentHome',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.otherParentHome'),
        conditional: conditionals.ifAge16OrLessConditional
    },
    {
        value: 'workedOvernight',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.workedOvernight'),
        conditional: conditionals.isWorkerConditional
    },
    {
        value: 'secondaryHome',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.secondaryHome')
    },
    {
        value: 'sleptAtFriends',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.sleptAtFriends')
    },
    {
        value: 'restaurant',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.restaurant')
    },
    {
        value: 'hotelForWork',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.hotelForWork'),
        conditional: conditionals.isWorkerConditional
    },
    {
        value: 'hotelForVacation',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.hotelForVacation')
    },
    {
        value: 'studying',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.studying'),
        conditional: conditionals.isStudentConditional
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:departurePlaceOtherChoices.other')
    }
];

export const onDemandChoices: ChoiceType[] = [
    {
        value: 'pickupAtOrigin',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:onDemandChoices.pickupAtOrigin', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'joinedStop',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:onDemandChoices.joinedStop', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:onDemandChoices.no')
    }
];

export const noWorkTripReasonChoices: ChoiceType[] = [
    {
        value: 'remoteWorkOrWorkAtHome',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.remoteWorkOrWorkAtHome')
    },
    {
        value: 'onStrike',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.onStrike'),
        hidden: true
    },
    {
        value: 'leaveSicknessPersonalReason',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.leaveSicknessPersonalReason')
    },
    {
        value: 'noWork',
        label: (t: TFunction) => t('choices:noWorkTripReasonChoices.noWork')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const noSchoolTripReasonChoices: ChoiceType[] = [
    {
        value: 'distanceLearning',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.distanceLearning')
    },
    {
        value: 'schoolWasClosed',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.schoolWasClosed')
    },
    {
        value: 'leaveSicknessPersonalReason',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.leaveSicknessPersonalReason')
    },
    {
        value: 'strike',
        label: (t: TFunction) => t('choices:noSchoolTripReasonChoices.strike'),
        hidden: true
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const educationalAttainment: ChoiceType[] = [
    {
        value: 'secondaryEducationOrLess',
        label: (t: TFunction) => t('choices:educationalAttainment.secondaryEducationOrLess')
    },
    {
        value: 'postSecondaryBelowBachelorEducation',
        label: (t: TFunction) => t('choices:educationalAttainment.postSecondaryBelowBachelorEducation')
    },
    {
        value: 'bachelorOrHigher',
        label: (t: TFunction) => t('choices:educationalAttainment.bachelorOrHigher')
    },
    ...preferNotToAnswer
];

export const workPlaceBeforeLeaveTypeChoices: ChoiceType[] = [
    {
        value: 'onLocation',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onLocation', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'hybrid',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.hybrid', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithUsualPlace',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onTheRoadWithUsualPlace', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'onTheRoadWithoutUsualPlace',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.onTheRoadWithoutUsualPlace', {
                nickname,
                count: countPersons
            });
        }
    },
    {
        value: 'remote',
        label: (t: TFunction, interview, path) => {
            const activePerson = odSurveyHelpers.getPerson({ interview, path });
            const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
            const countPersons = odSurveyHelpers.countPersons({ interview });
            return t('choices:workPlaceBeforeLeaveTypeChoices.remote', {
                nickname,
                count: countPersons
            });
        }
    }
];

export const transitModesChoices: ChoiceType[] = [
    {
        value: 'walk',
        label: (t: TFunction) => t('choices:transitModesChoices.walk')
    },
    {
        value: 'transitBus',
        label: (t: TFunction) => t('choices:transitModesChoices.transitBus'),
        conditional: customConditionals.isCurrentSegmentNotTransitBusCustomConditional
    },
    {
        value: 'transitOnDemand',
        label: (t: TFunction) => t('choices:transitModesChoices.transitOnDemand'),
        conditional: customConditionals.stationServedByTADCustomConditional
    },
    {
        value: 'carDriver',
        label: (t: TFunction) => t('choices:transitModesChoices.carDriver'),
        conditional: conditionals.hasDrivingLicenseConditional
    },
    {
        value: 'carPassenger',
        label: (t: TFunction) => t('choices:transitModesChoices.carPassenger')
    },
    ...other
];

export const intercityModesChoices: ChoiceType[] = [
    {
        value: 'walk',
        label: (t: TFunction) => t('choices:intercityModesChoices.walk')
    },
    {
        value: 'bicycle',
        label: (t: TFunction) => t('choices:intercityModesChoices.bicycle')
    },
    {
        value: 'carDriver',
        label: (t: TFunction) => t('choices:intercityModesChoices.carDriver'),
        conditional: conditionals.hasDrivingLicenseConditional
    },
    {
        value: 'carPassenger',
        label: (t: TFunction) => t('choices:intercityModesChoices.carPassenger')
    },
    {
        value: 'taxi',
        label: (t: TFunction) => t('choices:intercityModesChoices.taxi')
    },
    {
        value: 'transit',
        label: (t: TFunction) => t('choices:intercityModesChoices.transit')
    },
    ...otherWithoutSpecify
];

export const paidForParkingChoices: ChoiceType[] = [
    {
        value: 'noWorker',
        label: (t: TFunction) => t('choices:paidForParkingChoices.noWorker'),
        conditional: customConditionals.isDestinationWorkCustomConditional
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:paidForParkingChoices.no'),
        conditional: customConditionals.isDestinationNotWorkCustomConditional
    },
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:paidForParkingChoices.yes')
    },
    {
        value: 'noPark',
        label: (t: TFunction) => t('choices:paidForParkingChoices.noPark')
    },
    ...dontKnow
];

export const subwayLineChoices: ChoiceType[] = [
    {
        value: 'stm_2',
        label: (t: TFunction) => t('choices:subwayLineChoices.stm_2')
    },
    {
        value: 'stm_1',
        label: (t: TFunction) => t('choices:subwayLineChoices.stm_1')
    },
    ...dontKnow
];

export const planeStationChoices: ChoiceType[] = [
    {
        value: 'YUL',
        label: (t: TFunction) => t('choices:planeStationChoices.YUL')
    },
    {
        value: 'YHU',
        label: (t: TFunction) => t('choices:planeStationChoices.YHU')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const intercityRailStationChoices: ChoiceType[] = [
    {
        value: 'centralStation',
        label: (t: TFunction) => t('choices:intercityRailStationChoices.centralStation')
    },
    {
        value: 'dorvalStation',
        label: (t: TFunction) => t('choices:intercityRailStationChoices.dorvalStation')
    },
    {
        value: 'coteauStation',
        label: (t: TFunction) => t('choices:intercityRailStationChoices.coteauStation')
    },
    {
        value: 'saintLambertStation',
        label: (t: TFunction) => t('choices:intercityRailStationChoices.saintLambertStation')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const intercityBusStationChoices: ChoiceType[] = [
    {
        value: 'gareAutocarsMTL',
        label: (t: TFunction) => t('choices:intercityBusStationChoices.gareAutocarsMTL')
    },
    {
        value: 'terminusMegabus',
        label: (t: TFunction) => t('choices:intercityBusStationChoices.terminusMegabus')
    },
    {
        value: 'YUL',
        label: (t: TFunction) => t('choices:intercityBusStationChoices.YUL')
    },
    {
        value: 'terminusKirkland',
        label: (t: TFunction) => t('choices:intercityBusStationChoices.terminusKirkland')
    },
    {
        value: 'terminusLongueuil',
        label: (t: TFunction) => t('choices:intercityBusStationChoices.terminusLongueuil')
    },
    ...otherWithoutSpecify,
    ...dontKnow
];

export const usualWorkPlaceCommutingModes: ChoiceType[] = [
    {
        value: 'carDriver',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.carDriver')
    },
    {
        value: 'carPassenger',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.carPassenger')
    },
    {
        value: 'transit',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.transit')
    },
    {
        value: 'walk',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.walk')
    },
    {
        value: 'bike',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.bike')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.other'),
        conditional: conditionals.householdWithoutTwoWheelConditional
    },
    {
        value: 'otherMotor',
        label: (t: TFunction) => t('choices:usualWorkPlaceCommutingModes.otherMotor'),
        conditional: conditionals.householdWithTwoWheelConditional
    }
];

export const carParkingsHome: ChoiceType[] = [
    {
        value: 'private',
        label: (t: TFunction) => t('choices:carParkingsHome.private')
    },
    {
        value: 'stickers',
        label: (t: TFunction) => t('choices:carParkingsHome.stickers')
    },
    {
        value: 'onStreet',
        label: (t: TFunction) => t('choices:carParkingsHome.onStreet')
    }
];

export const bikesharingMembership: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:bikesharingMembership.yes')
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:bikesharingMembership.no')
    },
    ...dontKnow
];

export const disabilities: ChoiceType[] = [
    {
        value: 'hearing',
        label: (t: TFunction) => t('choices:disabilities.hearing'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'visual',
        label: (t: TFunction) => t('choices:disabilities.visual'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'cognitiveOrPsychic',
        label: (t: TFunction) => t('choices:disabilities.cognitiveOrPsychic'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'mentalHealth',
        label: (t: TFunction) => t('choices:disabilities.mentalHealth'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'intellectualOrTSA',
        label: (t: TFunction) => t('choices:disabilities.intellectualOrTSA'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'motor',
        label: (t: TFunction) => t('choices:disabilities.motor'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'chronicIllness',
        label: (t: TFunction) => t('choices:disabilities.chronicIllness'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'speechOrLanguageDisorder',
        label: (t: TFunction) => t('choices:disabilities.speechOrLanguageDisorder'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'fineMotorSkills',
        label: (t: TFunction) => t('choices:disabilities.fineMotorSkills'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:disabilities.other'),
        conditional: conditionals.personDisabilityIsNotPreferNotToAnswer
    },
    ...preferNotToAnswer
];

export const mobilityAssistiveDevices: ChoiceType[] = [
    {
        value: 'crutchOrCane',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.crutchOrCane'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'whiteCane',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.whiteCane'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'serviceOrGuideDog',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.serviceOrGuideDog'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'manualWheelchair',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.manualWheelchair'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'motorisedWheelchair',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.motorisedWheelchair'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'walkerOrRollator',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.walkerOrRollator'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'threeOrFourwheeledScooter',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.threeOrFourwheeledScooter'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'noSpecificDevice',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.noSpecificDevice'),
        conditional: conditionals.personMobilityDeviceNotPreferNotToAnswer
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.other'),
        conditional: conditionals.personMobilityDeviceNotExclusiveAnswer
    },
    {
        value: 'preferNotToAnswer',
        label: (t: TFunction) => t('choices:mobilityAssistiveDevices.preferNotToAnswer'),
        conditional: conditionals.personMobilityDeviceNotNone
    }
];

export const paratransitFrequencies: ChoiceType[] = [
    {
        value: 'never',
        label: (t: TFunction) => t('choices:paratransitFrequencies.never')
    },
    {
        value: '1orMorePerYear',
        label: (t: TFunction) => t('choices:paratransitFrequencies.1orMorePerYear')
    },
    {
        value: '1to3daysPerMonth',
        label: (t: TFunction) => t('choices:paratransitFrequencies.1to3daysPerMonth')
    },
    {
        value: '1to4daysPerWeek',
        label: (t: TFunction) => t('choices:paratransitFrequencies.1to4daysPerWeek')
    },
    {
        value: '5to7daysPerWeek',
        label: (t: TFunction) => t('choices:paratransitFrequencies.5to7daysPerWeek')
    }
];

export const paratransitFrequenciesTransit: ChoiceType[] = [
    {
        value: 'never',
        label: (t: TFunction) => t('choices:paratransitFrequenciesTransit.never'),
        conditional: conditionals.doesNotUseTransitConditional
    },
    {
        value: '1orMorePerYear',
        label: (t: TFunction) => t('choices:paratransitFrequenciesTransit.1orMorePerYear')
    },
    {
        value: '1to3daysPerMonth',
        label: (t: TFunction) => t('choices:paratransitFrequenciesTransit.1to3daysPerMonth')
    },
    {
        value: '1to4daysPerWeek',
        label: (t: TFunction) => t('choices:paratransitFrequenciesTransit.1to4daysPerWeek')
    },
    {
        value: '5to7daysPerWeek',
        label: (t: TFunction) => t('choices:paratransitFrequenciesTransit.5to7daysPerWeek')
    }
];

export const toddlerDaycareMode: ChoiceType[] = [
    {
        value: 'walk',
        label: (t: TFunction) => t('choices:toddlerDaycareMode.walk')
    },
    {
        value: 'bicycle',
        label: (t: TFunction) => t('choices:toddlerDaycareMode.bicycle')
    },
    {
        value: 'car',
        label: (t: TFunction) => t('choices:toddlerDaycareMode.car')
    },
    {
        value: 'transit',
        label: (t: TFunction) => t('choices:toddlerDaycareMode.transit')
    },
    ...otherWithoutSpecify
];

export const hasOmittedTripsActivities: ChoiceType[] = [
    {
        value: 'work',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.work')
    },
    {
        value: 'shopping',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.shopping')
    },
    {
        value: 'pickupDropOff',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.pickupDropOff')
    },
    {
        value: 'visitFriends',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.visitFriends')
    },
    {
        value: 'leisure',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.leisure')
    },
    {
        value: 'health',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.health')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:hasOmittedTripsActivities.other')
    }
];

export const hasOmittedTripsModes: ChoiceType[] = [
    {
        value: 'walk',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.walk')
    },
    {
        value: 'bicycle',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.bicycle')
    },
    {
        value: 'carDriver',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.carDriver')
    },
    {
        value: 'carPassenger',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.carPassenger')
    },
    {
        value: 'transit',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.transit')
    },
    {
        value: 'other',
        label: (t: TFunction) => t('choices:hasOmittedTripsModes.other')
    }
];

export const householdType: ChoiceType[] = [
    {
        value: 'multigenerationalFamily',
        label: (t: TFunction) => t('choices:householdType.multigenerationalFamily'),
        conditional: conditionals.hasHouseholdSize3OrMoreConditional
    },
    {
        value: 'manyFamilies',
        label: (t: TFunction) => t('choices:householdType.manyFamilies'),
        conditional: conditionals.hasHouseholdSize3OrMoreConditional
    },
    {
        value: 'oneFamilyWithOther',
        label: (t: TFunction) => t('choices:householdType.oneFamilyWithOther'),
        conditional: conditionals.hasHouseholdSize3OrMoreConditional
    },
    {
        value: 'coupleWithChild',
        label: (t: TFunction) => t('choices:householdType.coupleWithChild'),
        conditional: conditionals.hasHouseholdSize3OrMoreConditional
    },
    {
        value: 'coupleWithoutChild',
        label: (t: TFunction) => t('choices:householdType.coupleWithoutChild'),
        conditional: conditionals.hasHouseholdSize2Conditional
    },
    {
        value: 'parentWithChild',
        label: (t: TFunction) => t('choices:householdType.parentWithChild')
    },
    {
        value: 'noFamily',
        label: (t: TFunction) => t('choices:householdType.noFamily')
    }
];

export const didRespondForCorrectAssignedDateChoices: ChoiceType[] = [
    {
        value: 'yes',
        label: (t: TFunction) => t('choices:didRespondForCorrectAssignedDateChoices.yes')
    },
    {
        value: 'no',
        label: (t: TFunction) => t('choices:didRespondForCorrectAssignedDateChoices.no')
    }
];

export const didNotRespondForCorrectAssignedDateReasons: ChoiceType[] = [
    {
        value: 'didNotNoticeAssignedDate',
        label: (t: TFunction) => t('choices:didNotRespondForCorrectAssignedDateReasons.didNotNoticeAssignedDate')
    },
    {
        value: 'onVacationOrOutsideMontrealRegion',
        label: (t: TFunction) =>
            t('choices:didNotRespondForCorrectAssignedDateReasons.onVacationOrOutsideMontrealRegion')
    },
    {
        value: 'didNotKnowTripsForAtLeastOneHouseholdMember',
        label: (t: TFunction) =>
            t('choices:didNotRespondForCorrectAssignedDateReasons.didNotKnowTripsForAtLeastOneHouseholdMember')
    },
    {
        value: 'tripsNotRepresentativeOfUsualTravelHabits',
        label: (t: TFunction) =>
            t('choices:didNotRespondForCorrectAssignedDateReasons.tripsNotRepresentativeOfUsualTravelHabits')
    },
    {
        value: 'atLeastOneHouseholdMemberDidNotMakeAnyTrip',
        label: (t: TFunction) =>
            t('choices:didNotRespondForCorrectAssignedDateReasons.atLeastOneHouseholdMemberDidNotMakeAnyTrip')
    },
    {
        value: 'tooManyTripsToDeclareTooLong',
        label: (t: TFunction) => t('choices:didNotRespondForCorrectAssignedDateReasons.tooManyTripsToDeclareTooLong')
    },
    ...otherWithoutSpecify
];

export const anyTripModeFrequenciesChoices: ChoiceType[] = [
    {
        value: 'neverOrRarely',
        label: (t: TFunction) => t('choices:anyTripModeFrequenciesChoices.neverOrRarely')
    },
    {
        value: '1to3daysPerMonth',
        label: (t: TFunction) => t('choices:anyTripModeFrequenciesChoices.1to3daysPerMonth')
    },
    {
        value: '1dayPerWeek',
        label: (t: TFunction) => t('choices:anyTripModeFrequenciesChoices.1dayPerWeek')
    },
    {
        value: '2to4daysPerWeek',
        label: (t: TFunction) => t('choices:anyTripModeFrequenciesChoices.2to4daysPerWeek')
    },
    {
        value: '5DaysOrMorePerWeek',
        label: (t: TFunction) => t('choices:anyTripModeFrequenciesChoices.5DaysOrMorePerWeek')
    }
];

export const attitudinalChoices: ChoiceType[] = [
    {
        value: '-2',
        label: (t: TFunction) => t('choices:attitudinalChoices.-2')
    },
    {
        value: '-1',
        label: (t: TFunction) => t('choices:attitudinalChoices.-1')
    },
    {
        value: '0',
        label: (t: TFunction) => t('choices:attitudinalChoices.0')
    },
    {
        value: '1',
        label: (t: TFunction) => t('choices:attitudinalChoices.1')
    },
    {
        value: '2',
        label: (t: TFunction) => t('choices:attitudinalChoices.2')
    }
];

export const barriersChoices: ChoiceType[] = [
    {
        value: '0',
        label: (t: TFunction) => t('choices:barriersChoices.0')
    },
    {
        value: '1',
        label: (t: TFunction) => t('choices:barriersChoices.1')
    },
    {
        value: '2',
        label: (t: TFunction) => t('choices:barriersChoices.2')
    },
    {
        value: '3',
        label: (t: TFunction) => t('choices:barriersChoices.3')
    },
    {
        value: '4',
        label: (t: TFunction) => t('choices:barriersChoices.4')
    },
    {
        value: '-1',
        label: (t: TFunction) => t('choices:barriersChoices.-1')
    }
];

export const accessCodeConfirmChoices: ChoiceType[] = [
    {
        value: 'accessCodeConfirmOk',
        label: (t: TFunction) => t('choices:accessCodeConfirmChoices.accessCodeConfirmOk')
    }
];

export const vehicleOccupancyExtraChoices: ChoiceType[] = [
    {
        value: 'dontKnow',
        label: (t: TFunction) => t('choices:vehicleOccupancyExtraChoices.dontKnow'),
        conditional: customConditionals.isProxyCustomConditional
    }
];
