// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customHelpPopup from '../../common/customHelpPopup';

// Adapter la phrase si un seul enfant de 0-4ans avec le nickname et age.
// Pour les conditions SI EP garderie ET au moins un enfant de 0-4ans ET aucun dép. reconduire/aller chercher à une garderie/CPE (shp)
export const toddlerDaycare: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycare',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycare'),
    helpPopup: customHelpPopup.toddlerDaycareHelpPopup,
    choices: choices.yesNo,
    conditional: customConditionals.toddlerDaycareCustomConditional,
    validations: validations.requiredValidation
};

// Adapter la phrase selon le nombre d'enfants
// Liste des membres du ménage + "une autre personne"
export const toddlerDaycareDropoff: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.toddlerDaycareDropoff',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycareDropoff'),
    choices: choices.yesNo,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const toddlerDaycareDropoffMode: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycareDropoffMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycareDropoffMode'),
    choices: choices.toddlerDaycareMode,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

// Adapter la phrase selon le nombre d'enfants
// Liste des membres du ménage + "une autre personne"
export const toddlerDaycarePickup: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.toddlerDaycarePickup',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycarePickup'),
    choices: choices.yesNo,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const toddlerDaycarePickupMode: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycarePickupMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycarePickupMode'),
    choices: choices.toddlerDaycareMode,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTrips: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.hasOmittedTrips',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('omissions:hasOmittedTrips', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.yesNo,
    conditional: conditionals.hasOmittedTripsConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTripsIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'omissions.hasOmittedTripsIntro',
    containsHtml: true,
    text: (t: TFunction) => t('omissions:hasOmittedTripsIntro'),
    conditional: conditionals.hasOmittedTripsSpecifyConditional
};

export const hasOmittedTripsActivity: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.hasOmittedTripsActivity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:hasOmittedTripsActivity'),
    choices: choices.hasOmittedTripsActivities,
    conditional: conditionals.hasOmittedTripsSpecifyConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTripsMode: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.hasOmittedTripsMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:hasOmittedTripsMode'),
    choices: choices.hasOmittedTripsModes,
    conditional: conditionals.hasOmittedTripsSpecifyConditional,
    validations: validations.requiredValidation
};

export const buttonCompleteLongDistanceSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteLongDistanceSection',
    label: (t: TFunction) => t('omissions:buttonCompleteLongDistanceSection'),
    conditional: defaultConditional
};
